### ISSUE TITLE
提供更多可调用接口

### ISSUE THREAD

**Issue by HelloMitsuha** [only52607/LuaMiraiForAndroid#10]
**另开Issues到[#86](https://github.com/only52607/lua-mirai/issues/86)**

**Comment by only52607** [comment]
最近有点忙没有及时回复，你代码中member对象的isAdministrator方法属于kotlin里的扩展方法，当前版本还没有添加该方法的支持，可暂时先通过member对象中的`permission`来判断成员权限，可以参考下面的代码输出成员权限：
```
print(event.group:get(QQ).permission)
```
这个issue可以到[lua-mirai](https://github.com/only52607/lua-mirai/issues)下另开。
