### ISSUE TITLE
Http模块不执行

### ISSUE THREAD

**Issue by chorblack** [only52607/LuaMiraiForAndroid#2]
**bug类型**
Http模块不执行，测试了一言和我自己写的

**截图说明**
![QQ图片20210829153605](https://user-images.githubusercontent.com/67499253/131242595-bc4c1745-2fc3-44d9-a32b-4885d46f246c.jpg)
------------
![QQ图片20210829153601](https://user-images.githubusercontent.com/67499253/131242608-dd53ce24-dd48-44f6-95e7-1a5f54c9b526.jpg)
------------
![QQ图片20210829153556](https://user-images.githubusercontent.com/67499253/131242616-c58ba687-dcf3-4178-b552-4a16594c6306.jpg)
------------

**Comment by chorblack** [comment]
又好了,换成json库不执行了

**Comment by only52607** [comment]
Fixed in 1.0-alpha.4 :d42864116a438cbb3c9af55519d6a3b6c1946ed8
